CREATE OR REPLACE TRIGGER check_stock BEFORE INSERT OR UPDATE ON sale_item 
FOR EACH ROW EXECUTE PROCEDURE check_stock();

--CREATE OR REPLACE TRIGGER check_stock BEFORE UPDATE ON sale_item 
--FOR EACH ROW EXECUTE PROCEDURE check_stock();
